name: Rollback Management

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Select the target branch to rollback (delete)'
        required: true
        type: choice
        options:
          - AdhLdcrPrdS3
          - AdhYdxPrdS3
      backup_branch:
        description: 'Enter the backup branch to use for rollback'
        required: true

jobs:
  manage-rollback:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure all history is fetched
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup environment
      run: |
        TARGET_BRANCH="${{ github.event.inputs.target_branch }}"
        BACKUP_BRANCH="${{ github.event.inputs.backup_branch }}"
        TIMESTAMP=$(TZ=Asia/Tokyo date +'%Y/%m/%d %H:%M')
        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
        echo "BACKUP_BRANCH=${BACKUP_BRANCH}" >> $GITHUB_ENV
        echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

    - name: Delete the target branch
      run: |
        git push origin --delete ${{ env.TARGET_BRANCH }}

    - name: Create new branch from backup branch
      run: |
        git checkout -b ${{ env.TARGET_BRANCH }} origin/${{ env.BACKUP_BRANCH }}
        git push origin ${{ env.TARGET_BRANCH }}

    - name: Update EditFileRetry in backup branch
      run: |
        git checkout ${{ env.BACKUP_BRANCH }}
        echo "${{ env.TIMESTAMP }} ${{ env.TARGET_BRANCH }} rollback" >> .github/workflows/EditFileRetry
        git config user.email "no-reply@example.com"
        git config user.name "GitHub Action"
        git add .github/workflows/EditFileRetry
        git commit -m "Add rollback timestamp to EditFileRetry"
        git push origin ${{ env.BACKUP_BRANCH }}

    - name: Update EditFileRetry in develop_yl_ga branch
      run: |
        git checkout develop_yl_ga
        echo "${{ env.TIMESTAMP }} ${{ env.TARGET_BRANCH }} rollback" >> .github/workflows/EditFileRetry
        git config user.email "no-reply@example.com"
        git config user.name "GitHub Action"
        git add .github/workflows/EditFileRetry
        git commit -m "Add rollback timestamp to EditFileRetry"
        git push origin develop_yl_ga

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Rollback ${{ env.TARGET_BRANCH }} to ${{ env.BACKUP_BRANCH }}"
        branch: ${{ env.BACKUP_BRANCH }}
        base: ${{ env.TARGET_BRANCH }}
        title: "Rollback ${{ env.TARGET_BRANCH }} to ${{ env.BACKUP_BRANCH }}"
        body: "This PR rolls back ${{ env.TARGET_BRANCH }} to the state of ${{ env.BACKUP_BRANCH }}."
